apiVersion: v1
kind: Secret
metadata:
  name: secrets-env
type: Opaque
stringData:
  GUNICORN_WORKERS: "2"
  SITE_URL: "https://author-tools.ietf.org"
  DT_LATEST_DRAFT_URL: "http://dt-datatracker.datatracker.svc/api/rfcdiff-latest-json"
  # SENTRY_DSN: "" secret from vault
