name: Kustomize Config Check

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'k8s/**'

jobs:
  kustomize-config-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Test with dry run
        run: |
          kubectl kustomize ./k8s
          kubectl apply --dry-run=client --kustomize ./k8s
